class Doc2Vec:
  size: int
  min_count: int
  iter: int

  def __init__(*args, **kwargs): ...

  def build_vocab(*args, **kwargs): ...

  def train(*args, **kwargs): ...

  def corpus_count(*args, **kwargs): ...
